version: 2.1
orbs:
  ruby: circleci/ruby@2.3.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
